version: '3.7'

services:
  kafka1:
    image: bitnami/kafka:2.2.1
    hostname: kafka1
    ports:
      - "9092:9092"
    environment:
      TZ: Asia/Shanghai
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181/kafka
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/logs
      

    volumes:
      - type: volume
        source: kafka-data
        target: /bitnami/kafka
      
    
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
          - "node.hostname==node1"
      restart_policy:
        condition: on-failure
    networks:
      - cluster-net

  kafka2:
    image: bitnami/kafka:2.2.1
    hostname: kafka2
    ports:
      - "9093:9092"
    environment:
      TZ: Asia/Shanghai
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181/kafka
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/logs
    

    volumes:
      - type: volume
        source: kafka-data
        target: /bitnami/kafka
     
    
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
          - "node.hostname==node2"
      restart_policy:
        condition: on-failure
    networks:
      - cluster-net
  kafka3:
    image: bitnami/kafka:2.2.1
    hostname: kafka3
    ports:
      - "9094:9092"
    environment:
      TZ: Asia/Shanghai
      KAFKA_ZOOKEEPER_CONNECT: zoo1:2181,zoo2:2181,zoo3:2181/kafka
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_LOG_DIRS: /bitnami/kafka/logs
    

    volumes:
      - type: volume
        source: kafka-data
        target: /bitnami/kafka
      
    
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
          - "node.hostname==node3"
      restart_policy:
        condition: on-failure
    networks:
      - cluster-net
  kafka-manager:
    image: kafkamanager/kafka-manager
    hostname: kafka-manager
    ports:
      - "9000:9000"
    environment:
      TZ: Asia/Shanghai
      ZK_HOSTS: zoo1:2181,zoo2:2181,zoo3:2181
      KAFKA_MANAGER_AUTH_ENABLED: "true"
      KAFKA_MANAGER_USERNAME: admin
      KAFKA_MANAGER_PASSWORD: admin

    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
          - "node.hostname==node1"
      restart_policy:
        condition: on-failure
    networks:
      - cluster-net
networks:
  cluster-net:
    external: true
volumes:
  kafka-data:
