version: '3.7'

services:
  haproxy:
    image: haproxy:2.1.3-alpine
    hostname: haproxy
    ports: 
      - "1080:1080"
      - "13306:13306"
    environment:
      TZ: Asia/Shanghai
    configs:
      - source: haproxy-config
        target: /usr/local/etc/haproxy/haproxy.cfg
    deploy:
      replicas: 1
      mode: replicated
      placement:
        constraints:
          - "node.hostname==node1"
      restart_policy:
        condition: on-failure
    command: haproxy -f /usr/local/etc/haproxy/haproxy.cfg
    networks:
      - cluster-net
    
networks:
  cluster-net:
    external: true
configs:
  haproxy-config:
    file: ./haproxy.cfg